{{with .Values}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .config.name }}
  namespace: {{ .namespace }}
  labels:
    group: {{ .group }}
    stage: {{ .stage }}

data:
  application.properties: |-
    server.port = {{ .port }}
    spring.application.name= {{ .name }}
    com.test.check= "test"
{{end}}
