apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    group: {{ .Values.group }}
    stage: {{ .Values.stage }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.templateApp }}
  ports:
    - protocol: 'TCP'
      port: {{ .Values.port }}
  type: ClusterIP